name: windchime
description: "A Mindfulness App for Meditation, Sleep, and Focus"
publish_to: "none"
version: 0.1.0+9

# License information
license: GPL-3.0
homepage: https://github.com/ghostp13409/windchime
repository: https://github.com/ghostp13409/windchime

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  provider: ^6.1.1
  just_audio: ^0.9.36
  audioplayers: ^6.4.0
  path: ^1.8.0
  path_provider: ^2.1.4
  sqflite: ^2.4.0
  sqflite_common_ffi: any
  sqflite_common_ffi_web: any
  intl: 0.20.2
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.32
  flutter_launcher_icons: ^0.14.3
  haptic_feedback: ^0.5.1+1
  url_launcher: ^6.1.12
  http: ^1.1.0
  file_picker: ^10.1.9
  device_info_plus: ^10.1.0
  package_info_plus: ^8.3.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    # App images
    - assets/images/logo.png
    - assets/images/about/profile.png

    # Bundled audio files (smaller files only)
    - assets/sounds/meditation/Anxiety.mp3
    - assets/sounds/meditation/Focus.mp3
    - assets/sounds/meditation/Sleep.mp3
    - assets/sounds/meditation/happy.mp3
    - assets/sounds/startup/bell.wav
    - assets/sounds/startup/completetask.mp3
    - assets/sounds/startup/smallbell.mp3
    - assets/sounds/meditation/statechange/breath_in.wav
    - assets/sounds/meditation/statechange/breath_out.wav
    - assets/sounds/meditation/statechange/hold.wav
    - assets/sounds/meditation/statechange/rest.wav

# Flutter Launcher Icons configuration

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_version: 21
